# Generated by Django 5.0.6 on 2026-05-24 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('staff_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Staff ID must follow format S{YY}-{NNNN} e.g. S43-0094', regex='^S\\d{2}-\\d{4}$')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('committee', 'Committee'), ('head_of_school', 'Head of School'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_first_login', models.BooleanField(default=True, help_text='Forces password creation on first access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'ssc_users',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(help_text='SSC File Number e.g. A048. Auto-generated or imported for legacy.', max_length=10, unique=True)),
                ('_file_sequence', models.PositiveIntegerField(help_text='Internal integer for sequential generation. Do not edit.', unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('school_branch', models.CharField(choices=[('primary', 'Primary'), ('college', 'College'), ('other', 'Other')], max_length=20)),
                ('designation', models.CharField(max_length=255)),
                ('date_joined_school', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Set by Admin after Chairman approves Savings Change Form', max_digits=12)),
                ('residential_address', models.TextField()),
                ('permanent_home_address', models.TextField()),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('social_media_handle', models.CharField(blank=True, default='', max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('local_government_area', models.CharField(max_length=100)),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_address', models.TextField()),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_place_of_work', models.CharField(blank=True, default='', max_length=255)),
                ('membership_status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('exited', 'Exited Employment')], default='pending', max_length=20)),
                ('is_legacy', models.BooleanField(default=False, help_text='True if imported via legacy CSV — file number preserved as-is')),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('officer_in_charge', models.CharField(blank=True, default='', max_length=255)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('consecutive_savings_months', models.PositiveIntegerField(default=0, help_text='Resets to 0 when a month is missed. 6 required for loan/surety eligibility.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'db_table': 'ssc_member_profiles',
                'ordering': ['file_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffIDRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Format: S{YY}-{NNNN} e.g. S43-0094', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Staff ID must follow format S{YY}-{NNNN} e.g. S43-0094', regex='^S\\d{2}-\\d{4}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive IDs cannot be used to register or login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_staff_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff ID Registry',
                'verbose_name_plural': 'Staff ID Registry',
                'db_table': 'ssc_staff_id_registry',
                'ordering': ['staff_id'],
            },
        ),
    ]
