# Generated by Django 5.0.6 on 2026-05-24 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^S\\(\\d{2}\\)-\\d{4}$', 'Format must be S(YY)-NNNN')]),
        ),
    ]
