# Generated by Django 5.0.6 on 2026-05-24 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^S\\d{2}-\\d{4}$', 'Format must be SYY-NNNN, e.g. S43-0094')]),
        ),
    ]
