# Generated by Django 5.0.6 on 2026-05-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_staff_id'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuretyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.PositiveSmallIntegerField(help_text='1=self-surety, 2-6=external sureties')),
                ('is_self_surety', models.BooleanField(default=False)),
                ('amount_guaranteed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_liability', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('released', 'Released'), ('defaulted', 'Transferred (Default)')], default='pending', max_length=15)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sureties', to='loans.loanapplication')),
                ('surety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surety_records', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'ssc_surety_records',
                'ordering': ['layer'],
                'unique_together': {('loan', 'surety')},
            },
        ),
    ]
