# Generated by Django 5.0.6 on 2026-05-24 16:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ordinary_savings', 'Ordinary Savings'), ('termly_dues', 'Termly Dues'), ('profit_share', 'Profit Share'), ('adjustment', 'Adjustment'), ('legacy_import', 'Legacy Import')], default='ordinary_savings', max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=32)),
                ('gregorian_date', models.DateField(default=django.utils.timezone.now)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('verified_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('verified_by_role', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'ssc_savings_ledger',
                'ordering': ['-gregorian_date', '-id'],
            },
        ),
    ]
