# Generated by Django 5.0.6 on 2026-05-26 05:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('suretyship_committed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'ssc_member_balances',
            },
        ),
        migrations.CreateModel(
            name='SavingsChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))])),
                ('savings_balance_at_request', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_balance_at_request', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('effective_hijri_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_hijri_year', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_hijri_display', models.CharField(blank=True, default='', max_length=50)),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_savings_changes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_change_requests', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'ssc_savings_change_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=50)),
                ('gregorian_date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('ordinary_savings', 'Ordinary Savings'), ('termly_dues', 'Termly Dues'), ('profit_share', 'Profit Share'), ('adjustment', 'Adjustment'), ('legacy_import', 'Legacy Import'), ('loan_repayment', 'Loan Repayment')], max_length=30)),
                ('details', models.CharField(max_length=255)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('verified_by_name', models.CharField(max_length=255)),
                ('verified_by_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_entries', to='accounts.memberprofile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Ledger Entry',
                'db_table': 'ssc_savings_ledger',
                'ordering': ['hijri_year', 'hijri_month', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermlyDuesCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'First Term 1445'", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=50)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('target_members', models.ManyToManyField(blank=True, help_text='Empty = all active members', related_name='dues_cycles', to='accounts.memberprofile')),
            ],
            options={
                'db_table': 'ssc_termly_dues_cycles',
                'ordering': ['-hijri_year', '-hijri_month'],
            },
        ),
    ]
