# Generated by Django 5.0.6 on 2026-05-26 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.TextField()),
                ('phone_numbers', models.CharField(max_length=100)),
                ('school_branch', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=255)),
                ('date_joined_cooperative', models.DateField()),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_saved', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_last_loan', models.DateField(blank=True, null=True)),
                ('amount_outstanding_prev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('purpose', models.TextField()),
                ('proposed_monthly_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_duration_months', models.PositiveSmallIntegerField(help_text='Maximum 6 months (SRS amended)')),
                ('repayment_start_hijri_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repayment_start_hijri_year', models.PositiveIntegerField(blank=True, null=True)),
                ('repayment_end_hijri_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repayment_end_hijri_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_sureties', 'Pending Surety Confirmation'), ('approved', 'Committee Approved'), ('hos_approved', 'HOS Approved — Active'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('defaulted', 'Defaulted')], default='submitted', max_length=20)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('committee_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('committee_decision_note', models.TextField(blank=True, default='')),
                ('hos_approved_at', models.DateTimeField(blank=True, null=True)),
                ('application_hijri_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('application_hijri_year', models.PositiveIntegerField(blank=True, null=True)),
                ('application_hijri_display', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='accounts.memberprofile')),
                ('committee_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_reviewed_loans', to=settings.AUTH_USER_MODEL)),
                ('hos_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_approved_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssc_loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_month', models.PositiveSmallIntegerField()),
                ('hijri_year', models.PositiveIntegerField()),
                ('hijri_display', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verified_by_name', models.CharField(max_length=255)),
                ('verified_by_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loanapplication')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssc_loan_repayment_ledger',
                'ordering': ['hijri_year', 'hijri_month'],
            },
        ),
    ]
